id = "initop-extension"
name = "TopSolid PP INI files"
version = "0.0.1"
schema_version = 1
authors = ["Ulrich Alt <ualt@west-gmbh.de>"]
description = "Extension for authoring and highlighting TopSolid INI files"
repository = "https://github.com/UlrichAlt/initop-extension"

[grammars.ini_top]
repository = "https://github.com/UlrichAlt/tree-sitter-initop"
commit = "30d319cc66e9f5d3c04b18aa9753634849bbb7d2"
